#!/usr/bin/env python3
"""Generate docs/REFERENCE.md — the human-browsable index of every skill, command,
agent, and hook — from the frontmatter itself, so it cannot drift from the territory.
check-scaffold regenerates and diffs it; edit frontmatter, never the output file.
Usage: python3 .claude/scripts/build-reference.py [output-path]"""

import ast
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ROOT = Path(__file__).resolve().parents[2]
# The chassis is DERIVED, not listed: a skill absent from skillOverrides is always-on. Same source
# of truth check-scaffold's tier check uses, so the two agree by construction rather than by luck.
# TOOLS stays hand-listed — the tool/lane split has no on-disk signal (**Pinned:** isn't one; 30
# skills carry it, including lane skills like kubernetes).
TOOLS = {
    "env-uv",
    "tracking-mlflow",
    "tracking-wandb",
    "config-hydra",
    "config-omegaconf",
    "data-dvc",
    "hpo-optuna",
}


def frontmatter(path: Path) -> dict:
    m = re.match(r"(?s)\A---\n(.*?)\n---\n", path.read_text())
    if not m:
        return {}
    if yaml:
        try:
            return yaml.safe_load(m.group(1)) or {}
        except Exception:
            return {}
    d = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            k, _, v = line.partition(":")
            d[k.strip()] = v.strip()
    return d


def one_liner(desc: str, limit: int = 170) -> str:
    text = " ".join((desc or "").split())
    m = re.match(r"(.{20,}?[.!?])\s", text + " ")
    s = m.group(1) if m else text
    if len(s) > limit:
        s = s[: limit - 1].rsplit(" ", 1)[0] + "…"
    return s


def cell(value: object) -> str:
    """Collapse whitespace and escape `|` so a value can't break out of its table column.
    The hook Event column carries matchers like `Edit|Write`, which silently added a fourth
    cell to a three-column table until this existed."""
    return " ".join(str(value or "").split()).replace("|", "\\|")


# `<Event>(<matcher>) hook|guard — <summary>` prefix; the table's Event column already says it.
HOOK_PREFIX = re.compile(
    r"^\s*[A-Za-z]+(?:\([^)]*\))?\s+(?:hook|guard)\s*[:—-]\s*", re.IGNORECASE
)


def hook_line(path: Path, limit: int = 170) -> str:
    """One-line summary from the hook's own header — a module docstring (.py) or the first
    comment line after the shebang (.sh). Reading only `#` comments missed every Python hook,
    which is how ten of thirteen rows shipped blank."""
    text = path.read_text()
    if path.suffix == ".py":
        try:
            doc = ast.get_docstring(ast.parse(text)) or ""
        except SyntaxError:
            doc = ""
        first = doc.strip().split("\n", 1)[0]
    else:
        first = ""
        for line in text.splitlines()[1:]:
            s = line.strip()
            if s.startswith("#") and len(s) > 2:
                first = s.lstrip("#").strip()
            break
    first = HOOK_PREFIX.sub("", first)
    return " ".join(first.split())[:limit]


def main() -> None:
    out_path = (
        Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "REFERENCE.md"
    )
    settings = json.loads((ROOT / ".claude/settings.json").read_text())
    overrides = settings.get("skillOverrides", {})

    skills = {}
    for p in sorted((ROOT / ".claude/skills").glob("*/SKILL.md")):
        name = p.parent.name
        if name == "_example":
            continue
        skills[name] = one_liner(str(frontmatter(p).get("description", "")))

    # A skill absent from skillOverrides is always-on. Derived rather than hardcoded so a new
    # chassis skill can't silently vanish from this file.
    chassis = set(skills) - set(overrides)

    lines = [
        "# Reference — every skill, command, agent, and hook",
        "",
        "> GENERATED by `.claude/scripts/build-reference.py` from the frontmatter — do not edit by",
        "> hand (check-scaffold fails when this file is stale; regenerate instead). One line per",
        "> component; the full depth lives in each component's own file.",
        "",
        "## Skills — chassis (always on)",
        "",
        "| Skill | What it carries |",
        "|---|---|",
    ]
    for n in sorted(chassis):
        lines.append(f"| [`{n}`](../.claude/skills/{n}/SKILL.md) | {cell(skills[n])} |")

    lines += [
        "",
        "## Skills — gated (flipped by `/intake` via `skillOverrides`)",
        "",
        "| Skill | Kind | Default | What it carries |",
        "|---|---|---|---|",
    ]
    for n in sorted(overrides):
        if n not in skills:
            continue
        kind = "tool" if n in TOOLS else "lane"
        lines.append(
            f"| [`{n}`](../.claude/skills/{n}/SKILL.md) | {kind} | {cell(overrides[n])} | {cell(skills[n])} |"
        )

    lines += ["", "## Commands", "", "| Command | Does |", "|---|---|"]
    for p in sorted((ROOT / ".claude/commands").glob("*.md")):
        name = p.stem
        if name == "_TEMPLATE":
            continue
        lines.append(
            f"| [`/{name}`](../.claude/commands/{name}.md) | {cell(one_liner(str(frontmatter(p).get('description', ''))))} |"
        )

    lines += [
        "",
        "## Agents",
        "",
        "| Agent | Does | Tools | Preloaded skills |",
        "|---|---|---|---|",
    ]
    for p in sorted((ROOT / ".claude/agents").glob("*.md")):
        name = p.stem
        if name == "_TEMPLATE":
            continue
        fm = frontmatter(p)
        lines.append(
            f"| [`{name}`](../.claude/agents/{name}.md) | {cell(one_liner(str(fm.get('description', ''))))} "
            f"| {cell(fm.get('tools', ''))} | {cell(fm.get('skills', '—'))} |"
        )

    lines += [
        "",
        "## Hooks (wired in `settings.json`)",
        "",
        "| Hook | Event | Does |",
        "|---|---|---|",
    ]
    wiring = []
    for event, entries in settings.get("hooks", {}).items():
        for entry in entries:
            matcher = entry.get("matcher", "")
            for hook in entry.get("hooks", []):
                name = Path(hook["command"]).name
                ev = f"{event} · {matcher}" if matcher else event
                wiring.append((name, ev))
    for name, ev in sorted(wiring):
        lines.append(
            f"| [`{name}`](../.claude/hooks/{name}) | {cell(ev)} | {cell(hook_line(ROOT / '.claude/hooks' / name))} |"
        )

    lines += [
        "",
        "Also: the policy canon in [`.claude/memory/policy/`](../.claude/memory/policy/), the live",
        "project state in [`.claude/memory/process/`](../.claude/memory/process/), and the process",
        "framework itself at [`PROCESS.md`](../PROCESS.md).",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({len(skills)} skills)")


if __name__ == "__main__":
    main()
